FROM continuumio/miniconda3:4.10.3p1

RUN conda install \
    numpy \
    pandas \
    matplotlib \
    jupyterlab \
    sqlalchemy \
    pymysql \
    scipy \
    seaborn

CMD ["jupyter-lab","--ip=0.0.0.0","--no-browser","--allow-root"]